// ============================================================
// Tipos del dominio - CENIT (GREENLOG)
// Sistema de Control Ambiental - Power Apps Code App
// Modelo basado en Plan Monitoreos v7 + Presupuesto 2026 DB
// ============================================================

// ── Enums / Union Types ─────────────────────────────────────
export type EstadoActividad   = 'Planeada' | 'En Ejecución' | 'Cerrada' | 'Pendiente Aprobación';
export type Prioridad         = 'Alta' | 'Media' | 'Baja';
export type EstadoAprobacion  = 'Pendiente' | 'Aprobado' | 'Rechazado';
export type SeccionApp        = 'dashboard' | 'planeacion' | 'ejecucion' | 'reportes';
export type ServicioApp       = 'none' | 'planeacion_ambiental' | 'provisiones';

export type TipoLugar         = 'Estación' | 'Línea' | 'Zona';
export type TipoPlaneacion    = 'Plan' | 'Adicional' | 'Emergencia';
export type FuentePresupuesto = 'OPEX' | 'CAPEX';

export type LineaOperativa =
  | 'Monitoreos'
  | 'ICAs'
  | 'Pagos'
  | 'S.Cumplimiento'
  | 'S. Contigencias'
  | 'S. Viabilidad'
  | 'S. Proyectos'
  | 'Servicios E'
  | 'Compensaciones estaciones'
  | 'Compensaciones e Inv'
  | 'Estudios Ambientales'
  | 'Servicios Generales'
  | 'Hojas de Ruta Sostenibilidad Ambiental'
  | 'Residuos peligrosos'
  | 'Herramienta Digital'
  | 'Inversion Ambiental Voluntaria'
  | 'Obras por Impuestos';

export type TipoCuenta = 'OPEX' | 'CAPEX' | 'PROVISIÓN' | 'PROVISIÓN CONTING' | 'Inversión ambiental';

export type MatrizAmbiental =
  | 'ARD'         // Aguas Residuales Domésticas
  | 'ARnD'        // Aguas Residuales No Domésticas
  | 'Aire'
  | 'Ruido'
  | 'Fuentes Fijas'
  | 'Suelos'
  | 'Fauna'
  | 'Concesión'
  | 'Piezómetros'
  | 'Recirculación'
  | 'Olores Ofensivos';

export type RecursoReceptor = 'Suelo' | 'Agua' | 'Aire' | 'Ruido';

// ── Interfaces principales ──────────────────────────────────

/** Actividad ambiental - entidad central de planeación */
export interface ActividadAmbiental {
  id: string;
  tarea: string;
  lineaOperativa: LineaOperativa;
  descripcion?: string;
  responsable: string;
  contrato?: string;
  zona: string;               // Zona geográfica CENIT
  estacion?: string;           // Estación específica dentro de la zona
  tipoLugar?: TipoLugar;       // Estación, Línea o Zona completa
  pk?: string;                 // PK si tipoLugar es 'Línea'
  fuentePresupuesto?: FuentePresupuesto;  // OPEX o CAPEX
  tipoPlaneacion?: TipoPlaneacion;        // Plan, Adicional o Emergencia
  anioPlaneacion?: number;                // Año que se está planeando (2026, 2027...)
  fechaInicio: string;
  fechaFin: string;
  fechaInicioReal?: string;
  fechaFinReal?: string;
  mes: string;                 // Mes de ejecución presupuestal
  estado: EstadoActividad;
  prioridad: Prioridad;
  cuenta: TipoCuenta;
  cumplimientoNormativo?: string;
  novedades?: string;
  porcentajeAvance: number;
  estadoAprobacion: EstadoAprobacion;
  aprobadoPor?: string;
  fechaAprobacion?: string;
  // Presupuesto
  presupuestoPlan?: number;
  presupuestoEjecutado?: number;
  presupuestoForecast?: number;
  // Matrices ambientales aplicables
  matricesAplicables?: MatrizAmbiental[];
  creadoEn?: string;
  actualizadoEn?: string;
  // Raw OPEX serialized data if generated by wizards
  opexDataRaw?: string;
}

/** Centro / Zona - datos de estaciones y presupuesto */
export interface CentroZona {
  id: string;
  nombre: string;
  totalEstaciones: number;
  presupuestoAsignado: number;
  presupuestoEjecutado: number;
  responsableZona?: string;
  emailZona?: string;
}

/** Estación - punto geográfico con sus matrices */
export interface Estacion {
  id: string;
  nombre: string;
  planta: string;
  zona: string;
  totalMonitoreos: number;
  // Matrices
  ard: boolean;
  arnd: boolean;
  ardSuelo: boolean;
  ardAgua: boolean;
  arndSuelo: boolean;
  arndAgua: boolean;
  concesionPozo: boolean;
  concesionCuerpo: boolean;
  concesionAcueducto: boolean;
  aire: boolean;
  fuentesFijas: boolean;
  ruido: boolean;
  fauna: boolean;
  piezometros: boolean;
  recirculacion: boolean;
  oloresOfensivos: boolean;
  observaciones?: string;
}

/** Presupuesto mensual por línea operativa */
export interface PresupuestoLinea {
  id: string;
  mes: string;
  lineaOperativa: LineaOperativa;
  contrato: string;
  zona: string;
  cuenta: TipoCuenta;
  responsable: string;
  plan: number;
  ejecutado: number;
  forecast: number;
  observacion?: string;
  necesidad?: string;
}

/** Permiso ambiental por estación */
export interface PermisoAmbiental {
  id: string;
  zona: string;
  estacion: string;
  // Vertimiento
  ardCuerpoAgua: boolean;
  arndCuerpoAgua: boolean;
  ardSuelo: boolean;
  arndSuelo: boolean;
  ardAlcantarillado: boolean;
  arndAlcantarillado: boolean;
  ardProyectoMIA: boolean;
  arndProyectoMIA: boolean;
  ardGestor: boolean;
  arndGestor: boolean;
  // Concesión
  concesionSubIndustrial: boolean;
  concesionSubDomestico: boolean;
  concesionSupIndustrial: boolean;
  concesionSupDomestico: boolean;
}

// ── Payload de creación ─────────────────────────────────────
export type NuevaActividadPayload = Omit<ActividadAmbiental, 'id' | 'creadoEn' | 'actualizadoEn'>;

export const FORM_INICIAL: NuevaActividadPayload = {
  tarea: '',
  lineaOperativa: 'Monitoreos',
  descripcion: '',
  responsable: '',
  contrato: '',
  zona: '',
  estacion: '',
  fechaInicio: '',
  fechaFin: '',
  mes: '',
  estado: 'Planeada',
  prioridad: 'Media',
  cuenta: 'OPEX',
  fuentePresupuesto: 'OPEX',
  tipoPlaneacion: 'Plan',
  tipoLugar: 'Estación',
  anioPlaneacion: new Date().getFullYear() + 1,
  cumplimientoNormativo: '',
  novedades: '',
  porcentajeAvance: 0,
  estadoAprobacion: 'Pendiente',
  presupuestoPlan: 0,
  presupuestoEjecutado: 0,
  presupuestoForecast: 0,
  matricesAplicables: [],
};

// ── Constantes de referencia ────────────────────────────────

export const ESTADOS_ACTIVIDAD: { value: EstadoActividad; label: string }[] = [
  { value: 'Planeada',             label: 'Planeada' },
  { value: 'En Ejecución',         label: 'En Ejecución' },
  { value: 'Pendiente Aprobación', label: 'Pendiente Aprobación' },
  { value: 'Cerrada',              label: 'Cerrada' },
];

export const PRIORIDADES: { value: Prioridad; label: string }[] = [
  { value: 'Alta',  label: 'Alta' },
  { value: 'Media', label: 'Media' },
  { value: 'Baja',  label: 'Baja' },
];

export const LINEAS_OPERATIVAS: { value: LineaOperativa; label: string }[] = [
  { value: 'Monitoreos',                              label: 'Monitoreos' },
  { value: 'ICAs',                                     label: 'Aseguramiento ICAs' },
  { value: 'Pagos',                                    label: 'Pagos Autoridades' },
  { value: 'S.Cumplimiento',                           label: 'Servicio Cumplimiento' },
  { value: 'S. Contigencias',                          label: 'Servicio Contingencias' },
  { value: 'S. Viabilidad',                            label: 'Servicio Viabilidad' },
  { value: 'S. Proyectos',                             label: 'Servicio Proyectos' },
  { value: 'Servicios E',                 label: 'Servicios E' },
  { value: 'Compensaciones estaciones',                label: 'Compensaciones Estaciones' },
  { value: 'Compensaciones e Inv',                     label: 'Compensaciones e Inversión' },
  { value: 'Estudios Ambientales',                     label: 'Estudios Ambientales' },
  { value: 'Servicios Generales',                      label: 'Servicios Generales' },
  { value: 'Hojas de Ruta Sostenibilidad Ambiental',   label: 'Hojas de Ruta Sostenibilidad' },
  { value: 'Residuos peligrosos',                      label: 'Residuos Peligrosos (RESPEL)' },
  { value: 'Herramienta Digital',                      label: 'Herramienta Digital' },
  { value: 'Inversion Ambiental Voluntaria',           label: 'Inversión Ambiental Voluntaria' },
  { value: 'Obras por Impuestos',                      label: 'Obras por Impuestos' },
];

/** Líneas operativas disponibles para el wizard de planeación unificado */
export interface LineaPlaneacionConfig {
  value: LineaOperativa;
  label: string;
  icon: string;            // emoji o código de icono
  descripcion: string;
  usaMatriz: boolean;      // true = monitoreos (selección de matriz → parámetros)
  lugarPorDefecto: TipoLugar;  // 'Estación' para monitoreos, 'Zona' para servicios
  categoria: 'Gestión Ambiental' | 'Iniciativas Tecnológicas' | 'Servicios HSE';
}

export const LINEAS_PLANEACION: LineaPlaneacionConfig[] = [
  { value: 'Monitoreos',       label: 'Monitoreos Ambientales',     icon: '🧪', descripcion: 'Parámetros de muestreo por estación/línea, vinculados a la matriz de monitoreo', usaMatriz: true,  lugarPorDefecto: 'Estación', categoria: 'Gestión Ambiental' },
  { value: 'ICAs',             label: 'Aseguramiento ICAs',         icon: '📋', descripcion: 'Ítems de pago para aseguramiento de ICAs por zona o estación', usaMatriz: false, lugarPorDefecto: 'Zona',     categoria: 'Gestión Ambiental' },
  { value: 'Residuos peligrosos', label: 'Disposición RESPEL',      icon: '♻️', descripcion: 'Ítems de disposición de residuos peligrosos por estación', usaMatriz: false, lugarPorDefecto: 'Estación', categoria: 'Gestión Ambiental' },
  { value: 'Servicios E', label: 'Servicios E', icon: '🌿', descripcion: 'Compensaciones ambientales y servicios ecosistémicos', usaMatriz: false, lugarPorDefecto: 'Zona', categoria: 'Gestión Ambiental' },
  { value: 'Compensaciones estaciones', label: 'Compensaciones Estaciones', icon: '🌱', descripcion: 'Compensaciones específicas de estaciones', usaMatriz: false, lugarPorDefecto: 'Estación', categoria: 'Gestión Ambiental' },
  { value: 'Estudios Ambientales', label: 'Estudios Ambientales',    icon: '📊', descripcion: 'Estudios y diagnósticos ambientales', usaMatriz: false, lugarPorDefecto: 'Zona', categoria: 'Gestión Ambiental' },
  { value: 'Hojas de Ruta Sostenibilidad Ambiental', label: 'Hojas de Ruta Sostenibilidad', icon: '🗺️', descripcion: 'Acciones de sostenibilidad ambiental', usaMatriz: false, lugarPorDefecto: 'Zona', categoria: 'Gestión Ambiental' },
  { value: 'Pagos',            label: 'Pagos y Publicaciones',      icon: '💳', descripcion: 'Pagos a autoridades ambientales y publicaciones', usaMatriz: false, lugarPorDefecto: 'Zona', categoria: 'Gestión Ambiental' },
  { value: 'Herramienta Digital', label: 'Herramienta de Cumplimiento', icon: '💻', descripcion: 'Herramientas digitales y tecnológicas', usaMatriz: false, lugarPorDefecto: 'Zona', categoria: 'Iniciativas Tecnológicas' },
  { value: 'Servicios Generales', label: 'Servicios Generales',     icon: '🔧', descripcion: 'Servicios generales y otras actividades sin muestreo', usaMatriz: false, lugarPorDefecto: 'Zona', categoria: 'Servicios HSE' },
];

export const TIPOS_LUGAR: { value: TipoLugar; label: string; descripcion: string }[] = [
  { value: 'Estación', label: 'Estación',      descripcion: 'Estación específica (punto fijo)' },
  { value: 'Línea',    label: 'Línea (PK)',     descripcion: 'Ubicación en línea por PK (kilómetro)' },
  { value: 'Zona',     label: 'Zona completa',  descripcion: 'Aplica a toda la zona geográfica' },
];

export const TIPOS_PLANEACION: { value: TipoPlaneacion; label: string; descripcion: string }[] = [
  { value: 'Plan',       label: 'Plan',       descripcion: 'Planeación normal del próximo año' },
  { value: 'Adicional',  label: 'Adicional',  descripcion: 'Monitoreo o servicio adicional durante el año en curso' },
  { value: 'Emergencia', label: 'Emergencia', descripcion: 'Situación de emergencia ambiental' },
];

export const FUENTES_PRESUPUESTO: { value: FuentePresupuesto; label: string; descripcion: string }[] = [
  { value: 'OPEX',  label: 'OPEX',  descripcion: 'Gasto operativo — presupuesto operacional' },
  { value: 'CAPEX', label: 'CAPEX', descripcion: 'Inversión de capital — obras o agencias' },
];

export const TIPOS_CUENTA: { value: TipoCuenta; label: string }[] = [
  { value: 'OPEX',                label: 'OPEX' },
  { value: 'CAPEX',               label: 'CAPEX' },
  { value: 'PROVISIÓN',           label: 'Provisión' },
  { value: 'PROVISIÓN CONTING',   label: 'Provisión Contingencias' },
  { value: 'Inversión ambiental', label: 'Inversión Ambiental' },
];

export const MATRICES_AMBIENTALES: { value: MatrizAmbiental; label: string }[] = [
  { value: 'ARD',               label: 'Aguas Residuales Domésticas (ARD)' },
  { value: 'ARnD',              label: 'Aguas Residuales No Domésticas (ARnD)' },
  { value: 'Aire',              label: 'Calidad de Aire' },
  { value: 'Ruido',             label: 'Ruido Ambiental' },
  { value: 'Fuentes Fijas',     label: 'Fuentes Fijas (Emisiones)' },
  { value: 'Suelos',            label: 'Suelos / Sedimentos' },
  { value: 'Fauna',             label: 'Fauna / Biodiversidad' },
  { value: 'Concesión',         label: 'Concesión de Agua' },
  { value: 'Piezómetros',       label: 'Piezómetros / Agua Subterránea' },
  { value: 'Recirculación',     label: 'Recirculación' },
  { value: 'Olores Ofensivos',  label: 'Olores Ofensivos' },
];

export const MESES: string[] = [
  'Enero','Febrero','Marzo','Abril','Mayo','Junio',
  'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre',
];

export const CONTRATOS: string[] = [
  'Chemilab', 'ETSA', 'Applus', 'Misión temporal', 'ASI', 'BQS',
  'TI', 'TWM', 'VQ Ingeniería', 'SAP', 'Pagos', 'Provisiones', 'Nuevo',
];

/** Zonas geográficas CENIT con sus estaciones */
export const ZONAS_ESTACIONES: Record<string, string[]> = {
  'Occidente': [
    'Mariquita','Fresno','Herveo','Manizales','Pereira','Cisneros',
    'Medellín','Cartago','Yumbo','Dagua','Buenaventura','Orito',
  ],
  'Centro': [
    'Chimita','Galán','Santa Rosa','Sebastopol','Vasconia',
    'STH Vasconia CIB','STH Variante Galán Chimita','STH Galán Chimita',
  ],
  'CLC': [
    'Banadía','Banadía-Bicentenario','Oripaya','Orú','Samoré','Toledo',
    'Villa del Rosario',
  ],
  'Oriente': [
    'Albán','Guaduero','Gualanday','Mansilla','Neiva','Puerto Salgar',
    'Salgar','Villeta','Tocancipa','Sutamarchán',
  ],
  'Llanos': [
    'Altos del Porvenir','Apiay','Araguaney','Monterrey','San Fernando',
    'Miraflores',
  ],
  'Norte': [
    'Ayacucho','Baranoa','Copey','Pozos Colorados',
  ],
  'Coveñas': [
    'Planta Coveñas','Retiro',
  ],
  'Transversal': [],
};

/** Zonas como array simple (para selects) */
export const ZONAS: string[] = Object.keys(ZONAS_ESTACIONES);

/** Responsables ambientales de CENIT */
export const RESPONSABLES: { nombre: string; email: string; zona: string }[] = [
  { nombre: 'Eliana Cortes',        email: 'eliana.cortes@cenit-transporte.com',              zona: 'Oriente' },
  { nombre: 'Sonia Matiz',          email: 'ambiental-zona-oriente@cenit-transporte.com',     zona: 'Oriente' },
  { nombre: 'Maria Ximena Puerto',  email: 'maria.puerto@cenit-transporte.com',               zona: 'Centro' },
  { nombre: 'Claudia Falla',        email: 'ambiental-zona-centro@cenit-transporte.com',      zona: 'Centro' },
  { nombre: 'Carmen Rosero',        email: 'carmen.rosero@cenit-transporte.com',               zona: 'Occidente' },
  { nombre: 'Adriana Paola Barrera',email: 'ambiental-zona-occidente@cenit-transporte.com',   zona: 'Occidente' },
  { nombre: 'Luis Alberto Peláez',  email: 'luis.pelaez@cenit-transporte.com',                 zona: 'Occidente' },
  { nombre: 'María Guerrero',       email: 'ambiental-zona-occidente@cenit-transporte.com',   zona: 'Occidente' },
  { nombre: 'Javier Hernández',     email: 'javier.hernandez@cenit-transporte.com',            zona: 'CLC' },
  { nombre: 'Juan Carlos Rojas',    email: 'ambiental-zona-canolimon@cenit-transporte.com',   zona: 'CLC' },
  { nombre: 'Darío Sánchez',        email: 'ambiental-zona-llanos@cenit-transporte.com',      zona: 'Llanos' },
  { nombre: 'Viviana González',     email: 'viviana.gonzalez@cenit-transporte.com',             zona: 'Norte' },
  { nombre: 'Luis Vera',            email: 'ambiental-zona-norte@cenit-transporte.com',       zona: 'Norte' },
  { nombre: 'Diana León',           email: 'ambiental-zona-coveñas@cenit-transporte.com',     zona: 'Coveñas' },
  { nombre: 'Diana Basto',          email: '',                                                  zona: 'Transversal' },
  { nombre: 'Juan Cardenas',        email: '',                                                  zona: 'Transversal' },
  { nombre: 'Viviana Buitrago',     email: '',                                                  zona: 'Transversal' },
  { nombre: 'Ivonne Angulo',        email: '',                                                  zona: 'Transversal' },
];

/** Presupuesto 2026 por zona - según HR Base */
export const PRESUPUESTO_ZONAS: CentroZona[] = [
  { id: '1', nombre: 'Occidente',   totalEstaciones: 12, presupuestoAsignado: 107733333, presupuestoEjecutado: 0 },
  { id: '2', nombre: 'Oriente',     totalEstaciones: 10, presupuestoAsignado: 89777778,  presupuestoEjecutado: 0 },
  { id: '3', nombre: 'Centro',      totalEstaciones: 5,  presupuestoAsignado: 44888889,  presupuestoEjecutado: 0 },
  { id: '4', nombre: 'Llanos',      totalEstaciones: 5,  presupuestoAsignado: 44888889,  presupuestoEjecutado: 0 },
  { id: '5', nombre: 'CLC',         totalEstaciones: 4,  presupuestoAsignado: 35911111,  presupuestoEjecutado: 0 },
  { id: '6', nombre: 'Coveñas',     totalEstaciones: 1,  presupuestoAsignado: 9853659,   presupuestoEjecutado: 0 },
  { id: '7', nombre: 'Norte',       totalEstaciones: 4,  presupuestoAsignado: 35911111,  presupuestoEjecutado: 0 },
  { id: '8', nombre: 'Transversal', totalEstaciones: 0,  presupuestoAsignado: 0,          presupuestoEjecutado: 0 },
];

/** Resumen presupuesto 2026 total (según Seguimiento sheet) */
export const PRESUPUESTO_RESUMEN = {
  totalPlan2026: 16_228_425_858,    // $16.2B COP
  gestionAmbiental: 16_228_425_858,
  aseguramientoICAs: 1_765_106_707,
  monitoreos: 5_596_379_440,         // Chemilab
  pagos: 4_816_300_882,
  serviciosCumplimiento: 4_292_361_298,
  contingencias: 292_421_676,
  compensaciones: 100_000_000,
  estudiosAmbientales: 330_107_472,
  herramientaDigital: 370_584_907,
  respel: 617_000_000,
  hojasRutaSostenibilidad: 188_533_333,
};
